### ISSUE TITLE
Macos Compilation problem

### ISSUE THREAD

**Issue by sbonaime** [micmacIGN/micmac#41]
Compilation stops at 14% :-(

```[ 14%] Building CXX object src/CMakeFiles/elise.dir/EtalonnagePolygone/CPP_ConvertPolygone.cpp.o
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:411:7: error: use of undeclared identifier 'XCreateWindow'
  w = XCreateWindow
      ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:426:3: error: use of undeclared identifier 'XMapWindow'
  XMapWindow(ded->_disp,w);
  ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:427:3: error: use of undeclared identifier 'XSelectInput'
  XSelectInput
  ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:439:6: error: use of undeclared identifier 'XWindowEvent'
     XWindowEvent(ded->_disp,w,ExposureMask,&glob_event);
     ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:440:6: error: use of undeclared identifier 'XMoveWindow'
     XMoveWindow(ded->_disp,w,p0.x,p0.y);
     ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:441:6: error: use of undeclared identifier 'XMapWindow'
     XMapWindow(ded->_disp,w);
     ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:448:7: error: use of undeclared identifier 'XChangeWindowAttributes'
      XChangeWindowAttributes(ded->_disp,w,CWBackingStore,&att);
      ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:477:5: error: use of undeclared identifier 'XRaiseWindow'
    XRaiseWindow(_devd->_disp,_w);
    ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:482:5: error: use of undeclared identifier 'XLowerWindow'
    XLowerWindow(_devd->_disp,_w);
    ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:489:5: error: use of undeclared identifier 'XMoveWindow'
    XMoveWindow(_devd->_disp,_w,aP.x,aP.y);
    ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:490:5: error: use of undeclared identifier 'XMapWindow'
    XMapWindow(_devd->_disp,_w);
    ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:521:23: error: use of undeclared identifier 'XDefaultRootWindow'
                /*_w*/XDefaultRootWindow(_devd->_disp),
                      ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:897:7: error: use of undeclared identifier 'XPutImage'
      XPutImage
      ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1028:2: error: use of undeclared identifier 'XCopyArea'
        XCopyArea
        ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1113:11: error: use of undeclared identifier 'XResizeWindow'
          XResizeWindow(_devd->_disp,_mother,_SzMere->x,_SzMere->y);
          ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1114:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_mother);
          ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1125:16: error: use of undeclared identifier 'XCreateWindow'
          _w = XCreateWindow
               ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1138:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_w);
          ^
/Users/foouser/git/micmac/src/xinterf/fen_x11.cpp:1141:11: error: use of undeclared identifier 'XSelectInput'
          XSelectInput
          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by rjanvier** [comment]
try to compile with the NO_X11 option enabled
`cmake path/to/mm -DNO_X11=1 `

**Comment by antochny** [comment]
Sorry I broke something try to update XQuartz with brew because I cannot reproduce it but I have different issue now with or without NO_X11 option : 

> fatal error: file '/Users/anthony/micmac/include/general/CMake_defines.h' has
      been modified since the precompiled header
      '/Users/anthony/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header
      '/Users/anthony/micmac/include/StdAfx.h.pch'

**Comment by antochny** [comment]
I ran inside build folder :
`cmake -DWITH_QT5=1 -DNO_X11=1 ..`

cmake seems ok but tells :
Ignoring X11 package...
X11 Not Found : pas de SaisieMasq

Then it did have an effect, but didn't solved it, I reached until :

> [ 97%] Building CXX object src/CMakeFiles/elise.dir/saisieQT/include_QT/moc_saisieQT_window.cpp.o
/Users/anthony/micmac/src/saisieQT/GlExtensions.cpp:7:10: fatal error: 
      'GL/gl.h' file not found
#include "GL/gl.h"
         ^~~~~~~~~

Meanwhile you were right as compiling with -DNO_X11=1 and without QT5 works to 100%

It didn't solved everything as I wanted QT5 but for a CLI only installation we have at least solution !

I'll keep using SaisieQT tools with the last (and updated) precompiled binaries.
And I'll wait a little bit more the see new GUI (GIMMI) working on OSX, if ever it's supposed to support OSX though :/

**Comment by rjanvier** [comment]
Well, thanks for the feedback,
openGL headers have a specific location on macOS.  I will look if we need to ifdef something here.
I will enable GIMMI on travis to see if it compiles on macOS. I have an "old" mac book pro with 10.14 but my system is not a clean one (a lot of brew dependencies installed) and compile times are prohibitives so I prefer to gather external feedback for now.

**Comment by rjanvier** [comment]
I pushed a fix, could you please pull the master branch, clean your cmake cache and try to build again (-DWITH_QT5=1 -DNO_X11=1)?
thanks.

**Comment by bonaime** [comment]
With commit  3670777a8c0f6a3c0da55a59e6c818bc6a6b6265 from
Date:   Sat Mar 2 14:42:52 2019 +0100
```
cmake   -DWITH_QT5=1  -DNO_X11=1 ..
-- -----> OpenGL found
-- -----> using Qt 5.9.7
-- -----> Compile with c++11 support
-- -- FLAG:  -std=gnu++11
-- -- Git executable found
-- Derniere revision git de MicMac : v1.0.beta13-400-g3670777a8
Ignoring X11 package...
X11 Not Found : pas de SaisieMasq
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bonaime/git/micmac/build
````

````
In file included from /Users/bonaime/git/micmac/include/StdAfx.h:28:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:653:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/typeinfo:61:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/exception:82:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstdlib:86:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
```

**Comment by antochny** [comment]
No issue on my side with cmake since the commit, but it didn't solve the GL issue yet, as I got a similar but different error :

> [ 92%] Building CXX object src/CMakeFiles/elise.dir/saisieQT/include_QT/moc_saisieQT_window.cpp.o
/Users/anthony/MicMac/src/saisieQT/GlExtensions.cpp:10:11: fatal error: 
      'GL/gl.h' file not found
        #include "GL/gl.h"
                 ^~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/elise.dir/saisieQT/GlExtensions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/anthony/MicMac/src/saisieQT/Engine.cpp:1:
In file included from /Users/anthony/MicMac/include/../src/uti_image/Digeo/MultiChannel.h:7:
In file included from /Users/anthony/MicMac/include/StdAfx.h:148:

**Comment by bonaime** [comment]
I solve my "'stdlib.h' file not found" problem with this link
https://discourse.slicer.org/t/building-on-mac-10-14-mojave/4554

I found and solve my last problem to compile  : 
In micmac/src/saisieQT/GlExtensions.cpp, I change from

````
#include "GlExtensions.h"

#if ELISE_windows
	#include <windows.h> 
#endif

#ifdef ELISE_Darwin
	#include "OpenGL/gl.h"
#else
	#include "GL/gl.h"
````
to 
````
#include "GlExtensions.h"

#if ELISE_windows
	#include <windows.h> 
#endif

#ifdef ELISE_Darwin
	#include "OpenGL/gl.h"
#else
	#include <OpenGL/gl.h>
````

so either MacOS is not well found or it is not the right include...

**Comment by antochny** [comment]
The solution of bonaime just above modifying the the cpp file worked !
However GIMMI is still not compiled, I'm gonna open a new thread as this one is resolved ;)

**Comment by rjanvier** [comment]
@antochny it's not resolved, since the fix proposed is not portable, but @sbonaime (thanks for testing) gave a good insight about what could be done. I will work on and it should be easy to fix. 
But before I want to fix  the "stdlib.h" because the `open macOS_SDK_headers_for_macOS_10.14.pkg` workaround won't work with the upcoming version of macOS.

**Comment by sbonaime** [comment]
@rjanvier I found my fix here
https://stackoverflow.com/questions/26745284/cmake-not-finding-gl-h-on-os-x

**Comment by rjanvier** [comment]
yes thanks, it was also the spirit of my fix, I know that apple GL headers are in openGL/gl.h. But like you did,  it's not properly "gated". So even if it works for you it will break things on other platforms.

**Comment by rjanvier** [comment]
@sbonaime, so it was the option "MacOS is not well discovered", but using brackets cleary won't hurt... ;)

Anyway... the main issue of this thread is odd because Travis tells me that all is ok with X11 on a fresh macOS 10.13 as well as on a fresh macOS 10.14. 

Could you both (@antochny too) please update to the latest branch, clear your cmake cache, run cmake without the -DNO_X11=1 and copy past here the result of the cmake run?

thanks a lot.

**Comment by sbonaime** [comment]
````
cmake   -DWITH_QT5=1   ../
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework
-- -----> OpenGL found
-- -----> using Qt 5.9.7
-- -----> Compile with c++11 support
-- -- FLAG:  -std=gnu++11
-- Found Git: /usr/local/bin/git (found version "2.21.0")
-- -- Git executable found
-- Derniere revision git de MicMac : v1.0.beta13-402-g0d84f4757
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /opt/X11/lib/libX11.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bonaime/git/micmac/build
````
But I have a problem at compilation 
````
fatal errorfatal error: fatal errorfatal error: : : fatal error: filefilefilefile  file '/Users/bonaime/git/micmac/include/general/CMake_defines.h''/Users/bonaime/git/micmac/include/general/CMake_defines.h'  '/Users/bonaime/git/micmac/include/general/CMake_defines.h'  '/Users/bonaime/git/micmac/include/general/CMake_defines.h''/Users/bonaime/git/micmac/include/general/CMake_defines.h' hashas  has has been  been beenbeen modified  has modifiedsincemodified   modifiedsince been  fatal errorsincethe :  modified theprecompiledsincethe    sinceprecompiled precompiledthe header  header  file header'/Users/bonaime/git/micmac/include/StdAfx.h.pch'the'/Users/bonaime/git/micmac/include/StdAfx.h.pch'precompiled      '/Users/bonaime/git/micmac/include/general/CMake_defines.h'washeaderprecompiled '/Users/bonaime/git/micmac/include/StdAfx.h.pch'was   '/Users/bonaime/git/micmac/include/StdAfx.h.pch' has builtbuilt washeaderbeen

was '/Users/bonaime/git/micmac/include/StdAfx.h.pch'built modified built was
 since
built the
 precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'fatal error : wasnotenote : note: built: note: please
please filepleaserebuild    rebuild'/Users/bonaime/git/micmac/include/general/CMake_defines.h'rebuildprecompiled    precompiledhasprecompiledheader  note  beenheaderheader: '/Users/bonaime/git/micmac/include/StdAfx.h.pch'   '/Users/bonaime/git/micmac/include/StdAfx.h.pch'modified'/Users/bonaime/git/micmac/include/StdAfx.h.pch'please


sincerebuild  theprecompiled  precompiledheader  header'/Users/bonaime/git/micmac/include/StdAfx.h.pch'
'/Users/bonaime/git/micmac/include/StdAfx.h.pch'please  rebuildwasnote  : builtprecompiled pleaseheader
  rebuild'/Users/bonaime/git/micmac/include/StdAfx.h.pch' precompiled
 noteheader:  '/Users/bonaime/git/micmac/include/StdAfx.h.pch'please
rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_SuperposImage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamMICMAC.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamApero.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_DefautChantierDescripteur.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/cParamXMLNew0.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamDigeo.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamChantierPhotogram.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 15%] Linking CXX static library libpoisson.a
[ 15%] Built target poisson
make: *** [all] Error 2
````

And without any options : 
```
cmake     ../
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- -----> Compile with c++11 support
-- -- FLAG:  -std=gnu++11
-- Found Git: /usr/local/bin/git (found version "2.21.0")
-- -- Git executable found
-- Derniere revision git de MicMac : v1.0.beta13-402-g0d84f4757
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /opt/X11/lib/libX11.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bonaime/git/micmac/build
```

There is also a compilation problem 
````
fatal error: fatal error: filefile '/Users/bonaime/git/micmac/include/general/CMake_defines.h'  '/Users/bonaime/git/micmac/include/general/CMake_defines.h'has  hasbeen  beenmodified  modifiedsince  sincethe  theprecompiled  precompiledheader  header'/Users/bonaime/git/micmac/include/StdAfx.h.pch'  '/Users/bonaime/git/micmac/include/StdAfx.h.pch'was  wasbuilt built

note: note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'please
rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
1 errorfatal error generated: .
file '/Users/bonaime/git/micmac/include/general/CMake_defines.h'1  errorhas generated .
been modified since the precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
fatal error: file '/Users/bonaime/git/micmac/include/general/CMake_defines.h' 1has been error  generatedmodified .
since the precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
fatal error: file '/Users/bonaime/git/micmac/include/general/CMake_defines.h' has been modified since the precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
1 error generated.
1 error generated.
fatal error: file '/Users/bonaime/git/micmac/include/general/CMake_defines.h' has been modified since the precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
1 error generated.
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamChantierPhotogram.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamApero.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_DefautChantierDescripteur.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamDigeo.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/cParamXMLNew0.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_ParamMICMAC.cpp.o] Error 1
fatal error: file '/Users/bonaime/git/micmac/include/general/CMake_defines.h' has been modified since the precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch' was built
note: please rebuild precompiled header '/Users/bonaime/git/micmac/include/StdAfx.h.pch'
1 error generated.
make[2]: *** [src/CMakeFiles/elise.dir/__/CodeGenere/File2String/Str_SuperposImage.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Linking CXX static library libpoisson.a
[ 13%] Built target poisson
make: *** [all] Error 2
````

**Comment by antochny** [comment]
I also had this and solve it in two ways ;
1/  re-running the make install 
2/ and/or sometimes restarting Xcode
Don't ask me why I just read it while googling, tried and it worked...

**Comment by sbonaime** [comment]
@antochny
1/ Yes it is a working !!! But why ??? Why a second make install solve the compilation problem of the first run ? 
2/ how do you "restart Xcode" ? I don't "start Xcode" to compile

**Comment by antochny** [comment]
@sbonaime 
1/ I don't know either ^^...
2/ I think you should have had install Xcode, just open it from applications folder. When I'm starting/restarting it before a new compile trial, I don't have to do solution 1/
Don't ask me why this weird behaviour of OSX :/

**Comment by rjanvier** [comment]
So if you clean your cache (remove your `CMakeCache.txt` file inside you build directory) and re-run 
`cmake   -DWITH_QT5=1   ../ && make -j` do you still have the issue reported here https://github.com/micmacIGN/micmac/issues/41#issue-240219022 ?

**Comment by sbonaime** [comment]
The problem is solved ! No more errors :-) There are quite a lot of different warnings 
Full log of compilation attached
[micmac_compilation_macos_07-03-19.txt](https://github.com/micmacIGN/micmac/files/2940509/micmac_compilation_macos_07-03-19.txt)

**Comment by mo8Zomo0** [comment]
hmm, I am trying to compile the source from git under MacOS 11.2.3 and the compile also fails.

Does not seem to matter if xcode (12.4) was not running (first attempt, running, running after restarting xcode, ...).
Also tried to rerun "cmake -DWITH_QT5=1 ../ && make -j" (or with -j4) with or without deleting CMakeCache.txt
No change in behaviour.

Consolidate compiler generated dependencies of target elise
[ 13%] Building CXX object src/CMakeFiles/elise.dir/xinterf/fen_x11.cpp.o
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:411:7: error: use of undeclared identifier 'XCreateWindow'
  w = XCreateWindow
      ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:426:3: error: use of undeclared identifier 'XMapWindow'
  XMapWindow(ded->_disp,w);
  ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:427:3: error: use of undeclared identifier 'XSelectInput'
  XSelectInput
  ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:439:6: error: use of undeclared identifier 'XWindowEvent'
     XWindowEvent(ded->_disp,w,ExposureMask,&glob_event);
     ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:440:6: error: use of undeclared identifier 'XMoveWindow'
     XMoveWindow(ded->_disp,w,p0.x,p0.y);
     ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:441:6: error: use of undeclared identifier 'XMapWindow'
     XMapWindow(ded->_disp,w);
     ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:448:7: error: use of undeclared identifier 'XChangeWindowAttributes'
      XChangeWindowAttributes(ded->_disp,w,CWBackingStore,&att);
      ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:477:5: error: use of undeclared identifier 'XRaiseWindow'
    XRaiseWindow(_devd->_disp,_w);
    ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:482:5: error: use of undeclared identifier 'XLowerWindow'
    XLowerWindow(_devd->_disp,_w);
    ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:489:5: error: use of undeclared identifier 'XMoveWindow'
    XMoveWindow(_devd->_disp,_w,aP.x,aP.y);
    ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:490:5: error: use of undeclared identifier 'XMapWindow'
    XMapWindow(_devd->_disp,_w);
    ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:521:23: error: use of undeclared identifier 'XDefaultRootWindow'
                /*_w*/XDefaultRootWindow(_devd->_disp),
                      ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:897:7: error: use of undeclared identifier 'XPutImage'
      XPutImage
      ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1028:2: error: use of undeclared identifier 'XCopyArea'
        XCopyArea
        ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1113:11: error: use of undeclared identifier 'XResizeWindow'
          XResizeWindow(_devd->_disp,_mother,_SzMere->x,_SzMere->y);
          ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1114:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_mother);
          ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1125:16: error: use of undeclared identifier 'XCreateWindow'
          _w = XCreateWindow
               ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1138:11: error: use of undeclared identifier 'XMapWindow'
          XMapWindow(_devd->_disp,_w);
          ^
/Users/user/src/git/micmac/src/xinterf/fen_x11.cpp:1141:11: error: use of undeclared identifier 'XSelectInput'
          XSelectInput
          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/elise.dir/xinterf/fen_x11.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/elise.dir/all] Error 2
make: *** [all] Error 2
